remote_theme: pages-themes/dinky@v0.2.0

plugins:
- jekyll-remote-theme

title: Saroj Adhikari
author: "Saroj Adhikari"

github_username: sarojadhikari

description: Saroj Adhikari, Assistant Professor of Physics, SUNY Plattsburgh 
logo: saroj_2020.jpg
github:
  is_project_page: false

header_pages:
  - news.md
  - tools.md
  - publications.md
  - cv/cv.md

future: true
