theme: minima
title: Saroj Adhikari
author: "Saroj Adhikari"

github_username: sarojadhikari

description: Saroj Adhikari, Assistant Professor of Physics, SUNY Plattsburgh 
logo: saroj_2020.jpg
github:
  is_project_page: false

header_pages:
  - publications.md
  - cv/cv.md