site_name: Saroj Adhikari
site_description: Personal Homepage of Saroj Adhikari

theme:
    name: material
    palette:
        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: black
          toggle:
            icon: material/brightness-7
            name: Switch to dark mode
        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: black
          toggle:
            icon: material/brightness-4
            name: Switch to light mode
    features:
        - navigation.tabs
        - navigation.top
        - search.highlight

plugins:
    - search:

markdown_extensions:
    - abbr
    - admonition
    - pymdownx.details
    - attr_list
    - md_in_html

nav:
    - Home: index.md
    - News: news.md
    - Teaching: teaching.md
    - Publications: publications.md

extra:
    analytics:
        provider: google
        property: !ENV GOOGLE_ANALYTICS_KEY

extra_css:
    - assets/stylesheets/extra.css
